### ISSUE TITLE
Error when adding new line in Add Records

### ISSUE THREAD

**Issue by tech41** [dfrnt-com/support.dfrnt.tech#11]
In the Add Records feature (which looks very useful!), I attempted to adding a new line before I entered anything in the first one. What I was expecting was to be able to add as many lines as needed, then go back and fill them. Not necessary, but it feels intuitive. 

It appears that the new line was actually created and is functional. 

<img width="594" alt="image" src="https://user-images.githubusercontent.com/66345289/219543906-c2999047-cf6e-4691-8596-91cf9cd87d7d.png">

<img width="476" alt="image" src="https://user-images.githubusercontent.com/66345289/219543945-b9f6b238-11ae-4ae4-aefb-78a7490162ef.png">

**Comment by hoijnet** [comment]
Looks like you made it to work based on the report but that the warning was unintuitive? The idea is to show issues until all is resolved. It might be that the checking should be done explicitly with a "check data button" on request instead of immediately?

I belive th add records section is one of those that should have an explainer video!!

Could you unpack more specifically what was not to expectation? Is seems you need to have entered data that is currently missing?

**Comment by tech41** [comment]
Yes that makes sense, the warning was unintuitive but it functioned as expected. And the warning message itself made sense (that a required property was missing). I think it was just that the warning message is a big popup that says 'error', so I thought it meant something was broken.

I like the idea of not checking immediately. What about checking when the 'Add' button is pressed?

**Comment by hoijnet** [comment]
Makes sense, I will review the UX and see how to make it more helpful. Thanks for bringing it to attention!

**Comment by hoijnet** [comment]
@tech41 The error message is adjusted now with the latest release that will be out today together with the upgrade to TerminusDB 11 for the hosting. It is designed to be less scary. Closing for now, feel free to reopen if you see this you still deem it is an issue!

<img width="667" alt="image" src="https://user-images.githubusercontent.com/144317/222049483-74ce33c9-0394-4aed-a146-5ccc6cea523c.png">

**Comment by hoijnet** [comment]
There is an off-by-one error there that is harder to solve, that is captured as an internal issue to be figured out.
