### ISSUE TITLE
Maximum call stack size exceeded error when trying to create an instance document

### ISSUE THREAD

**Issue by timathom** [dfrnt-com/support.dfrnt.tech#15]
**Describe the bug**
After loading the schema [available here](https://github.com/timathom/linked-art-terminusdb/tree/90722bf1fcee234e37433da7e83b8f95bc7f8eac), I try to create a new record for the entity called `Type` (subtype of `EntityType`) in my schema. As soon I click the button to add a new record for `Type`, the maximum call stack size error is thrown.

**Screenshot**
<img width="694" alt="Screenshot 2023-08-17 at 12 46 44 PM" src="https://github.com/dfrnt-com/support/assets/5334524/e7e9677c-b468-4eac-874f-68c4ae6262f9">

**Comment by hoijnet** [comment]
Thanks for the clear breakdown of sequence. I'll load the [CombinedLinkedArtSchema schema](https://github.com/timathom/linked-art-terminusdb/blob/90722bf1fcee234e37433da7e83b8f95bc7f8eac/schema/CombinedLinkedArtSchema.json) on my end to understand the issue better and come up with a fix for record creation. Sounds like a potential corner case with the @base being same across.

Will know more soon!

**Comment by hoijnet** [comment]
This should not be solved and checked so closing it. Please share if you have any remaining issues with them!
