### ISSUE TITLE
Data pointer incorrect name

### ISSUE THREAD

**Issue by tech41** [dfrnt-com/support.dfrnt.tech#7]
I created a data pointer; then created a sandbox data pointer using the 'Add Example Sandbox button'.

Viewing the pointers from Settings->Instance Admin->review data pointers, the names is correct:

<img width="514" alt="image" src="https://user-images.githubusercontent.com/66345289/215308378-e8b4a7dd-97c8-436c-93d0-4c856ef474a1.png">

However in the drop down it seems that my pointer is named 'Sandbox':

<img width="532" alt="image" src="https://user-images.githubusercontent.com/66345289/215308400-a3fd8c7d-ca87-4586-856d-cc252db45d7e.png">

Similarly on dfrnt.com/modeller, it looks like I have two pointers Sandbox and sandbox:

<img width="437" alt="image" src="https://user-images.githubusercontent.com/66345289/215308573-a5baca45-494c-43bb-a251-32d82297a3e9.png">

**Comment by hoijnet** [comment]
When creating a sandbox instance, a pointer is created automatically, I think it's the one that has the capital S. You can remove the pointers and recreate them with a different name. It is as per design, but perhaps it is confusing that the pointer is created automatically?

**Comment by tech41** [comment]
Ah ok I see now, I had not created a pointer for my data product. So I was incorrect thinking that the name was wrong. I suppose it was confusing to see two pointers both named 'sandbox'. 

One thing that might help would be adding a paragraph to Settings->Instance Admin explaining what exactly a pointer is? The paragraph defining a Data Product on that same page is a great summary and helpful.

**Comment by hoijnet** [comment]
Thanks for sharing that, I had another solution for adding pointers next to it previously and whilst simplifying that got removed, leaving only the data product view, including the pointers. I will merge the original documentation, it is missing for sure, thank you so much for it, no wonder it's confusing =)

**Comment by hoijnet** [comment]
The texts have been updates for the next minor release now to make them, specific to the pointer add screen, the following text was added:

> A DFRNT pointer is a selectable graph data product reference. It points to a specific branch of a TerminusDB data product. Work in DFRNT is always performed within a specific data Pointer. In this section, you configure the menu alternatives for data pointers, that point to specific data products and branches.

Please reopen if you see that this should be described further! Thanks a lot @tech41 for reporting the issue!!
